---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://home-yolink.erik-dc9.workers.dev/
polling_headers: ''
id: 93142
name: YoLink Temperature
refresh_interval: 60
